### ISSUE TITLE
How to copy existing FS into a folder/subvolume

### ISSUE THREAD

**Issue by elmystico** [mwilck/btrfs-clone#1]
?

I need to put a whole btrfs FS into existing btrfs FS that's not empty.

Can your code do it? Does it need to be modified? If so- can you do it, please?

**Comment by gaetanquentin** [comment]
i think you can

**Comment by clang88** [comment]
I know this is quite an old question/issue, but it's a really small change to the code. All you need to change is the
`def mount_root_subvol(mnt):` function. This is how I did it:
`def mount_root_subvol(mnt):
    td = mkdtemp()
    try:
        info = check_output([opts.btrfs, "filesystem", "show", mnt])
        line = info.decode("ascii").split("\n")[0]
        uuid = re.search(r"uuid: (?P<uuid>[-a-f0-9]*)", line).group("uuid")
        check_call(["mount", "-o", "subvolid=5", "UUID=%s" % uuid, td])
        atexit.register(umount_root_subvol, td)
    except:
        info = check_output([opts.btrfs, "subvolume", "show", mnt])
        line = info.decode("ascii").split("\n")[2]
        line2 = info.decode("ascii").split("\n")[6]
        print(line, line2)
        subvolid = line2.split("\t")[3]
        uuid = line.split("\t")[4]
        check_call(["mount", "-o", f"subvolid={subvolid}", "/dev/mapper/cachedev_0", td])
        atexit.register(umount_root_subvol, td)
    return (uuid, td)`

Granted, this is really just hacked together and not fully automatic (you need to change `/dev/mapper/cachedev_0` to the block-device on which the subvolume lives, automating that should be fairly easy), but other than that it seems to work as intended.

**Comment by clang88** [comment]
I know this is a rather old issue, but since I needed this aswell, I went ahead and hacked together a sort of solution. Not really posting this as a commit as it needs work, but it got the job done for me change function `def mount_root_subvol(mnt)` to:
```
def mount_root_subvol(mnt):
    td = mkdtemp()
    try:
        info = check_output([opts.btrfs, "filesystem", "show", mnt])
        line = info.decode("ascii").split("\n")[0]
        uuid = re.search(r"uuid: (?P<uuid>[-a-f0-9]*)", line).group("uuid")
        check_call(["mount", "-o", "subvolid=5", "UUID=%s" % uuid, td])
        atexit.register(umount_root_subvol, td)
    except:
        info = check_output([opts.btrfs, "subvolume", "show", mnt])
        line = info.decode("ascii").split("\n")[2]
        line2 = info.decode("ascii").split("\n")[6]
        print(line, line2)
        subvolid = line2.split("\t")[3]
        uuid = line.split("\t")[4]
        check_call(["mount", "-o", f"subvolid={subvolid}", "/dev/mapper/cachedev_0", td])#"UUID=%s" % uuid, td])
        atexit.register(umount_root_subvol, td)
    return (uuid, td)
```
You will need to change `/dev/mapper/cachedev_0` to whatever block-device your btrfs subvolume sits on. This way, the script attempts to first mount whatever path you point it at as top level subvolume and if that doesn't work (because it is a regular subvolume) it will mount the subvolume as the top-level on a temporary mount point and run through the rest of the script as normal.

**Comment by elmystico** [comment]
:-) better late than never
