### ISSUE TITLE
python grammar error (is vs ==)

### ISSUE THREAD

**Issue by dkragen** [mwilck/btrfs-clone#23]
Running the latest version elicited an error which flagged line 144, asking if == was meant instead of is.  Substituting == allowed the program to run.

**Comment by TheNighthawk99** [comment]
Same here.
Is this project managed or not?

**Comment by uzlonewolf** [comment]
Seeing as the last update was 4 years ago and there have never been any PRs merged in, I'm going to go with "No."  We'll see if @mwilck responds.

And PR #20 from over a year ago fixes this issue.

**Comment by mwilck** [comment]
#20 has been merged. Sorry for making you wait.

**Comment by uzlonewolf** [comment]
Thank you @mwilck !
