### ISSUE TITLE
Clone aborted with "failed to read stream from kernel: Broken Pipe"

### ISSUE THREAD

**Issue by SampsonF** [mwilck/btrfs-clone#25]
./btrfs-clone --dry-run -v /run/media/fcc/8T /run/media/fcc/z
unsharing mount namespace
OLD btrfs ae208b98-d49b-4542-91ae-e2cfce5cf8b0 mounted on /tmp/tmpgvZ7It
NEW btrfs 8b8782ab-09e0-4de6-b039-e76b4220a3b2 mounted on /tmp/tmpeI_iF4
Create readonly snapshot of '/tmp/tmpgvZ7It' in '/tmp/tmpgvZ7It/2c0eef8d68ac'
btrfs send -v /tmp/tmpgvZ7It/2c0eef8d68ac |
	 btrfs receive -v /tmp/tmpeI_iF4
btrfs property set -f /tmp/tmpeI_iF4/2c0eef8d68ac ro false
mv -f -t /tmp/tmpeI_iF4 -v /tmp/tmpgvZ7It/2c0eef8d68ac/.beeshome
mv -f -t /tmp/tmpeI_iF4 -v /tmp/tmpgvZ7It/2c0eef8d68ac/appdata.backup
mv -f -t /tmp/tmpeI_iF4 -v /tmp/tmpgvZ7It/2c0eef8d68ac/_btrbk_backup
mv -f -t /tmp/tmpeI_iF4 -v /tmp/tmpgvZ7It/2c0eef8d68ac/1
mv -f -t /tmp/tmpeI_iF4 -v /tmp/tmpgvZ7It/2c0eef8d68ac/2-dat
mv -f -t /tmp/tmpeI_iF4 -v /tmp/tmpgvZ7It/2c0eef8d68ac/restic_1
mv -f -t /tmp/tmpeI_iF4 -v /tmp/tmpgvZ7It/2c0eef8d68ac/wmb
mv -f -t /tmp/tmpeI_iF4 -v /tmp/tmpgvZ7It/2c0eef8d68ac/arm
mv -f -t /tmp/tmpeI_iF4 -v /tmp/tmpgvZ7It/2c0eef8d68ac/QVO
btrfs subvolume delete /tmp/tmpeI_iF4/2c0eef8d68ac
Using cloning strategy GenerationStrategy
split() takes no keyword arguments
Delete subvolume 5075 (no-commit): '/tmp/tmpgvZ7It/2c0eef8d68ac'

#./btrfs-clone  -v /run/media/fcc/8T /run/media/fcc/z
unsharing mount namespace
OLD btrfs ae208b98-d49b-4542-91ae-e2cfce5cf8b0 mounted on /tmp/tmpIShpfZ
NEW btrfs 8b8782ab-09e0-4de6-b039-e76b4220a3b2 mounted on /tmp/tmpaHGE2I
Create readonly snapshot of '/tmp/tmpIShpfZ' in '/tmp/tmpIShpfZ/28733abcafdf'
btrfs send -v /tmp/tmpIShpfZ/28733abcafdf |
	 btrfs receive -v /tmp/tmpaHGE2I
Error in send:
Protocol version requested: 1 (supported 2)
At subvol /tmp/tmpIShpfZ/28733abcafdf
ERROR: failed to read stream from kernel: Broken pipe

I/O operation on closed file
Delete subvolume 5076 (no-commit): '/tmp/tmpIShpfZ/28733abcafdf'

**Comment by mwilck** [comment]
> btrfs send -v /tmp/tmpIShpfZ/28733abcafdf |
> Protocol version requested: 1 (supported 2)

This looks like a problem between btrfsprogs and your kernel. I think you'll be able to reproducde this problem by just running `btrfs send` and `btrfs-receive`. It isn't caused by `btrfs-clone`, which simply calls these tools.

**Comment by SampsonF** [comment]
Yes you are correct.

Thank you for looking into this.

I have another issue btrfs-clone seems finisned, but not all subvols are cloned to new disk.  Will create new issue when I can re-produce it.
