### ISSUE TITLE
Add --keep-going mode to ignore errors

### ISSUE THREAD

**Issue by devurandom** [mwilck/btrfs-clone#6]
Would it be possible to add a `--keep-going` mode that would ignore errors, try to copy as much as possible of a snapshot or subvolume and then continue with the next subvolume or snapshot?

This would help with recovering a file system, e.g. for those being affected by the infamous bcache corruption bug (https://bugzilla.kernel.org/show_bug.cgi?id=203573).

**Comment by mwilck** [comment]
There is the `--ignore-errors` option, isn't that what you are looking for?
